cm_app/config/routes.rb
Rails.application.routes.draw do
  resources :studies
  resources :dashboards
  resources :notes
  resources :courses do
    resources :assignments
  end
  
  namespace :course do
    resources :assignments
  end
  
  devise_for :users
    root to: "dashboards#index"
    
  # resources :notes do
  #   collection do
  #     get 'search'
  #   end
  # end
  
    
    
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

cm_app/app/models/study.rb
class Study < ApplicationRecord
end

cm_app/app/controllers/studies_controller.rb
class StudiesController < ApplicationController
  before_action :set_study, only: %i[ show edit update destroy ]

  # GET /studies or /studies.json
  def index
    @studies = Study.all
    @courses = current_user.courses
    @notes = current_user.notes
  end

  # GET /studies/1 or /studies/1.json
  def show
  end

  # GET /studies/new
  def new
    @study = Study.new
  end

  # GET /studies/1/edit
  def edit
  end

  # POST /studies or /studies.json
  def create
    @study = Study.new(study_params)

    respond_to do |format|
      if @study.save
        format.html { redirect_to @study, notice: "Study was successfully created." }
        format.json { render :show, status: :created, location: @study }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @study.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /studies/1 or /studies/1.json
  def update
    respond_to do |format|
      if @study.update(study_params)
        format.html { redirect_to @study, notice: "Study was successfully updated." }
        format.json { render :show, status: :ok, location: @study }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @study.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /studies/1 or /studies/1.json
  def destroy
    @study.destroy
    respond_to do |format|
      format.html { redirect_to studies_url, notice: "Study was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_study
      @study = Study.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def study_params
      params.fetch(:study, {})
    end
end

cm_app/app/helpers/studies_helper.rb
module StudiesHelper
end

cm_app/app/views/studies/_form.html.erb
<%= form_with(model: study) do |form| %>
  <% if study.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(study.errors.count, "error") %> prohibited this study from being saved:</h2>

      <ul>
        <% study.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

cm_app/app/views/studies/edit.html.erb
<h1>Editing Study</h1>

<%= render 'form', study: @study %>

<%= link_to 'Show', @study %> |
<%= link_to 'Back', studies_path %>

cm_app/app/views/studies/index.html.erb
<p id="notice"><%= notice %></p>


<h1>Study Sesh</h1>
<div class='big help d-flex justify-content-center' id='movable'>
  <div class='help card'>
      <div class="settings">
          <button id="settings-btn" class="set-btn fas fa-cog fa-lg" type="button">settings</button>
      </div>
      <br>
      <div>
        <div class="container">
            <p id="pomo" class="top pomodoro active">Pomodoro</p>
            <p id="break" class="top break">Break</p>
        </div>
        
        <div class="timer" id="time" onload="setValue()">
            <p id='w-min' class="time">00</p>
            <p class="seperator">:</p>
            <p id="w-sec" class="time">00</p>
        </div>
        
        <div id="buttons">
            <button id="start" class="button is-primary is-large btn btn-primary">Start</button>
            &nbsp
            <button id="pause" class="button is-large btn btn-primary">Pause</button>
            <button id="reset" class="button is-large is-danger btn btn-primary">Reset</button>
            <button id="skip" class="button is-large is-danger btn btn-primary">Skip</button>
            <button id="skip-pomo" class="skip-pomo-btn fa-lg"></button>
        </div>
        
        <div class="cycles">
            <p class="pomo-counter">Pomodoros : </p>
            <p id="cycle">1</p>
            <p> / </p>
            <p id="total-cycles">4</p>
            
        </div>
        
        <div class="msg">
            <p id="message" class="msg-txt">Time to Work!</p>
        </div>
    
        <div class="settings-container" id="settings">
            <div class="settings-panel">
                <button id="settings-close" class="close-settings fa-2x"></button>
                <h3 class="setting-title timer-title">Timer Settings</h3>
                <h4>Pomodoro</h4> <input type="number" placeholder="25" value="25" class="input is-medium is-link" min="15"
                    max="30" id="setting-pomodoros">
                <h4>Short Break</h4><input type="number" placeholder="05" value="5" class="input is-medium is-link" min="2"
                    max="15" id="setting-break">
                <button id="setting-okay" class="button is-info okay-btn">Okay</button>
            </div>
        </div>
      </div>
    </div>
  </div>
  
  <div class='frameOverlay'></div>
      <div class='resizeable'>
        <div id='movable2'>
            <div class='handle'></div>
            <iframe width="560" height="315" src="https://www.youtube.com/embed/5qap5aO4i9A" 
            title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" 
            allowfullscreen class='card'></iframe>
        </div>
    </div>
    
    
    
<div class="card notes" id='movable3'>
    <div>
      <div class='container text-center'>
        <h2>Assignments</h2>
        <% @courses.each do |course| %>
            <% course.assignments.each do |assignment| %>
                <div class='card'>
                  <div class="row">
                    <div class="column">
                      <%= course.name %> <br>
                      <%= assignment.name %>
                    </div>
        
                    <div class='column'>
                      <%= assignment.date.strftime("DUE AT: %I:%M %p") %>
                      <br>
                      <%= assignment.date.strftime("%b %d") %>
                    </div>
                    <div class='column'>
                        <div class='btn btn-primary start ' id='mixBut' onclick="startCount()">
                          START
                        </div>
                        <div class='btn btn-danger stop' id='mixBut' onclick="stopCount()">
                          STOP
                        </div>
                        <p class='txt'></p>
                    </div>
                </div>
                </div>
          <% end %>
        <% end %>
      <br>
      <br>
      </div>  
    </div>
  </div>
    
  <%= javascript_pack_tag 'main'%>
  <%= javascript_pack_tag 'draggable'%>
  <%= stylesheet_link_tag params[:controller] %>

cm_app/app/views/studies/new.html.erb
<h1>New Study</h1>

<%= render 'form', study: @study %>

<%= link_to 'Back', studies_path %>

cm_app/app/views/studies/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_study_path(@study) %> |
<%= link_to 'Back', studies_path %>