cm_app/config/routes.rb
Rails.application.routes.draw do
  resources :studies
  resources :dashboards
  resources :notes
  resources :courses do
    resources :assignments
  end
  
  namespace :course do
    resources :assignments
  end
  
  devise_for :users
    root to: "dashboards#index"
    
  # resources :notes do
  #   collection do
  #     get 'search'
  #   end
  # end
  
    
    
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

cm_app/app/models/note.rb
class Note < ApplicationRecord
    belongs_to :user, class_name: 'User'
    
  class << self
    def search(query)
      rel = order("id")
      if query.present?
        rel = rel.where("title LIKE?", "%#{query}%")
      end
      rel
    end
  end
    
end

cm_app/app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_note, only: %i[ show edit update destroy ]

  # GET /notes or /notes.json
  def index
    @notes = current_user.notes.search(params[:q])
  end
  # GET /notes/1 or /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = current_user.notes.build
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes or /notes.json
  def create
    @note = current_user.notes.build(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: "Note was successfully created." }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1 or /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: "Note was successfully updated." }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def search
    @notes = Note.search(params[:q])
    render "index"
  end
  

  # DELETE /notes/1 or /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: "Note was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def note_params
      params.require(:note).permit(:title, :content)
    end
end

cm_app/app/helpers/notes_helper.rb
module NotesHelper
end

cm_app/app/views/notes/_form.html.erb
<%= form_with(model: note) do |form| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
        <% note.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <p><%= form.label :title %></p>
    <%= form.text_field :title %>
  </div>
  <br>

  <div class="field">
    <p><%= form.label :content %></p>
    <%= form.text_area :content %>
  </div>
  <br>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

cm_app/app/views/notes/edit.html.erb
<div class='card'>
    <center>
        <h1>Editing Note</h1>
        
        <%= render 'form', note: @note %>
        
        <%= link_to 'Back', url_for(:back), class: 'btn btn-primary' %>
        <%= link_to 'Delete', @note.destroy, class:'btn btn-danger'%>
    </center>
</div>

cm_app/app/views/notes/index.html.erb
<p id="notice"><%= notice %></p>


<div class="card">
  <div class='card-header'>
    <h2 class='d-flex justify-content-between'>
        <span>Notes</span>
        <%= link_to 'Add Note', new_note_path, class: 'btn btn-primary' %>
      </h2>
      
      
      <%= form_tag :notes, method: :get, class: "search" do %>
        <%= text_field_tag "q", params[:q] %>
        <%= submit_tag "search"%>
      <% end %>

    
    <div class="card-header" style="justify-content:center">
      <% @notes.each do |note| %>
      <div class='card-fancy'>
        <div class='assignment'>
          <%= link_to note do %>
            <h2><%= note.title %></h2>
          <%end%>
        </div>
      </div>
      <br>
      <% end %>
    </div>
  </div>
</div>

<br>

cm_app/app/views/notes/new.html.erb
<div class='card'>
    <center>
        <h1>New Note</h1>
        <%= render 'form', note: @note %>
        <br>
        <%= link_to 'Back', url_for(:back), class: 'btn btn-primary' %>
    </center>
</div>

cm_app/app/views/notes/search.html.erb
<%= form_tag(search_path, :method => "get") do %>
<div class="input-group">
    <%= search_field_tag :search, params[:q], placeholder: "Type ", class: "form-control" %>
    <div class="input-group-btn">
        <%= button_tag "Search for Notes", :class => 'btn btn-info glyphicon-search', :name=> nil%>
    </div>
</div>
<% end %> 

cm_app/app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>
<div class='card'>
    <center>
        <h1>
            <%= @note.title %>
            <%= link_to 'Edit', edit_note_path(@note), class: 'btn btn-outline' %> 
            <%= link_to 'Back', url_for(:back), class: 'btn btn-primary' %>
        </h1>
          
        
        <p class='fill'>
          <%= @note.content %>
        </p>
    </center>
</div>