cm_app/config/routes.rb
Rails.application.routes.draw do
  resources :studies
  resources :dashboards
  resources :notes
  resources :courses do
    resources :assignments
  end
  
  namespace :course do
    resources :assignments
  end
  
  devise_for :users
    root to: "dashboards#index"
    
  # resources :notes do
  #   collection do
  #     get 'search'
  #   end
  # end
  
    
    
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

cm_app/app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :course
  
  validates :status, inclusion: { in: ['not-started','in-progress','complete']}
  
  STATUS_OPTIONS = [
    ['Not Started','not-started'],
    ['In Progress','in-progress'],
    ['Complete','complete']
  ]
  
   class << self
    def search(query)
      rel = order("id")
      if query.present?
        rel = rel.where("name LIKE?", "%#{query}%")
      end
      rel
    end
  end
  
end

cm_app/app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_course
  before_action :set_assignment, only: [:show, :edit, :update, :destroy]

  # GET courses/1/assignments
  def index
    @assignments = @course.assignments.search(params[:q])
  end

  # GET courses/1/assignments/1
  def show
  end

  # GET courses/1/assignments/new
  def new
    @assignment = @course.assignments.build
  end

  # GET courses/1/assignments/1/edit
  def edit
  end

  # POST courses/1/assignments
  def create
    @assignment = @course.assignments.build(assignment_params)

    if @assignment.save
      redirect_to(@assignment.course)
    else
      render action: 'new'
    end
  end

  # PUT courses/1/assignments/1
  def update
    if @assignment.update(assignment_params)
      redirect_to(@assignment.course)
    else
      render action: 'edit'
    end
  end

  # DELETE courses/1/assignments/1
  def destroy
    @assignment.destroy

    redirect_to (@assignment.course)
  end
  
  def search
    @assignments = @course.assignments.search(params[:q])
    render "course"
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:course_id])
    end

    def set_assignment
      @assignment = @course.assignments.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def assignment_params
      params.require(:assignment).permit(:name, :description, :status, :date, :complete_time, :course_id)
    end
end

cm_app/app/helpers/assignments_helper.rb
module AssignmentsHelper
end

cm_app/app/views/assignments/_form.html.erb
<%= form_with(model: [@assignment.course, @assignment]) do |f| %>
  <% if @assignment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@assignment.errors.count, "error") %> prohibited this assignment from being saved:</h2>

      <ul>
      <% @assignment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.select :status, Assignment::STATUS_OPTIONS %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :complete_time %><br />
    <%= f.text_field :complete_time %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

cm_app/app/views/assignments/edit.html.erb
<div class='card'>
    <center>
        <h1>Editing assignment</h1>
        
        <%= render 'form' %>
        
        <%= link_to 'Back', url_for(:back), class: 'btn btn-primary' %>
        <%= link_to 'Delete', [@assignment.course, @assignment], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
    </center>
</div>

cm_app/app/views/assignments/index.html.erb
<h1>Assignments</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Status</th>
    <th>Date</th>
  </tr>

<% @assignments.each do |assignment| %>
  <tr>
    <td><%= assignment.name %></td>
    <td><%= assignment.description %></td>
    <td><%= assignment.status %></td>
    <td><%= assignment.date %></td>
    <td><%= link_to 'Show', [assignment.course, assignment] %></td>
    <td><%= link_to 'Edit', edit_course_assignment_path(assignment.course, assignment) %></td>
    <td><%= link_to 'Destroy', [assignment.course, assignment], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Assignment', new_course_assignment_path(params[:course_id]) %>

<div class="card">
  <div class="card-header">
    
    <h2 class='card-title d-flex justify-content-between'>
      <span>Courses</span>
      <%= link_to 'Add Course', new_course_path, class: 'btn btn-primary' %>
    </h2>
    
  </div>
</div>

cm_app/app/views/assignments/new.html.erb
<div class='card'>
    <center>
        <h1>New assignment</h1>
        
        <%= render 'form' %>
        
        <%= link_to 'Back', url_for(:back), class: 'btn btn-primary' %>
    </center>
</div>

cm_app/app/views/assignments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Back', course_path(@course), class:"btn btn-primary" %>
<div class="card">
  <div class="card-header">
    <h2>
      <%= @assignment.name %>
    </h2>
  
    <p>
      <%= @assignment.description %>
    </p>
  
    <div class="dropdown">
      <%= @assignment.status %>
    </div>
  
    <div>
      <%= @assignment.date.strftime("DUE AT: %I:%M %p") %>
    </div>
    
    <div class="topcorner">
      <%= link_to 'Edit', edit_course_assignment_path(@assignment.course, @assignment), class:"btn btn-outline-secondary" %> 
    </div>
  </div>
</div>